name: mapper_box
description: Simple wrapper to collect object conversion rules.
version: 1.0.0
repository: https://github.com/GlebBatykov/mapper_box

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
